version: "3.8"

services:
  web:
    build: ./services/web
    volumes:
      - ./services/web:/usr/src/app/
    env_file:
      - ./.env
    command: python manage.py run -h 0.0.0.0
    ports:
      - 5000:5000
    networks:
      - web
    entrypoint: ./entrypoint.sh
  db:
    image: postgres:14-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker_flask
      - POSTGRES_PASSWORD=docker_flask
      - POSTGRES_db=docker_flask
    networks:
      - web

volumes:
  postgres_data:

networks:
  web:
    name: docker_flask
    internal: true